FROM docker.io/library/ubuntu:latest

RUN apt update && \
apt upgrade -y && \
apt install curl wget -y && \
curl -sLO https://get.helm.sh/helm-v3.17.2-linux-amd64.tar.gz && \
tar xvfz helm-v3.17.2-linux-amd64.tar.gz linux-amd64/helm && \
mv linux-amd64/helm /usr/local/bin && \
rm -fvr helm-v3.17.2-linux-amd64.tar.gz linux-amd64

WORKDIR /

COPY --chmod=554 job/entrypoint.sh .

ENTRYPOINT ["/entrypoint.sh"]
