---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: metrics-catalog
  name: metrics-catalog
  namespace: olmv1-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-catalog
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: metrics-catalog
    spec:
      containers:
        - image: quay.io/eochieng/metrics-server-catalog:latest
          name: metrics-server-catalog
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: "RuntimeDefault"
            capabilities:
              drop:
                - ALL
          resources: {}
status: {}
