---
apiVersion: olm.operatorframework.io/v1
kind: ClusterCatalog
metadata:
  name: metrics-server-operators
  namespace: olmv1-system
spec:
  priority: -100
  source:
    image:
      pollIntervalMinutes: 5
      ref: quay.io/eochieng/metrics-server-catalog:latest
    type: Image
