---
apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: metrics-server
  namespace: metrics-server-system
spec:
  namespace: metrics-server-system
  serviceAccount:
    name: metrics-server-installer
  source:
    sourceType: Catalog
    catalog:
      packageName: metrics-server
      version: 3.12.0
