apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: chart-uploader
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/eochieng/uploader:latest
        name: chart-uploader
        resources: {}
      restartPolicy: Never
status: {}
